name: fest_app
description: fest_app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  sqflite:
  path:
  path_provider:
  shared_preferences:
  flutter_sticky_header:
  url_launcher:
  qr_code_scanner:
  archive:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true